### ISSUE TITLE
not working!

### ISSUE THREAD

**Issue by askfriends** [respecting/linkvertise-bypass#2]
i just tried this link and it didnt work, says bypassing but wont do anything. SS is attached.

https://linkvertise.com/186538/Beldelofbv?o=sharing

![Web capture_11-2-2021_233420_lem0ns me](https://user-images.githubusercontent.com/2517219/107682397-1bc0af80-6cc2-11eb-8d20-9bc5d028131b.jpeg)

**Comment by jonathanlin0** [comment]
yea same here

**Comment by respecting** [comment]
they have cors now, archiving.
